#pragma once
#include <vector>
#include <string>
#include <functional>

#include <Godot.hpp>
#include <KinematicBody2D.hpp>
#include <CollisionObject2D.hpp>
#include <Node.hpp>
#include <Node2D.hpp>
#include <Input.hpp>
#include <PackedScene.hpp>
#include <Vector2.hpp>
#include <Area2D.hpp>
#include <Sprite.hpp>
#include <OS.hpp>
#include <Timer.hpp>
#include <RandomNumberGenerator.hpp>
#include <Camera2D.hpp>
#include <InputEvent.hpp>
#include <TileMap.hpp>
#include <Tree.hpp>
#include <Array.hpp>
#include <ProgressBar.hpp>

#include "IPlayer.h"
#include "PlayerData.h"
#include "Player1.h"
#include "Player2.h"
#include "PlayerController.h"
#include "Bullet.h"
#include "Enemy.h"
#include "PlayerProduce.h"
#include "ProducePlayer1.h"
#include "ProducePlayer2.h"
#include "Sword.h"
#include "CameraController.h"
#include "Spike.h"

#include "SpiderAI.h"
#include "EnemySideChecker.h"
#include "Enemies.h"
//#include "Enemy.h"
#include "SimpleEnemyAI.h"
#include "FlowerAI.h"
#include "Generation.h"
//#include "PlayerController.h"
#include "SpawnPointChecker.h"
#include "Room.h"
#include "Destroyer.h"
#include "ClosedRoom.h"
#include "Door.h"
#include "SpawnEnemyController.h"
#include "SlimeAI.h"