# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
tool
class_name LocalizationKeys

const KEY_NAME = "KEY_NAME"
const KEY_PLAY = "KEY_PLAY"
const KEY_SETTINGS = "KEY_SETTINGS"
const KEY_LANGUAGE = "KEY_LANGUAGE"
const KEY_BACK = "KEY_BACK"
const KEY_QUIT = "KEY_QUIT"
const KEY_TITLE = "KEY_TITLE"
const KEY_SINGLE_MODE = "KEY_SINGLE_MODE"
const KEY_COOPERATIVE_MODE = "KEY_COOPERATIVE_MODE"
const KEY_AUTHORS = "KEY_AUTHORS"
const KEY_RETRY = "KEY_RETRY"
const KEY_GAME_OVER = "KEY_GAME_OVER"
const KEY_MENU = "KEY_MENU"
const KEY_MODE = "KEY_MODE"
const KEY_EFFECTS = "KEY_EFFECTS"
const KEY_MUSIC = "KEY_MUSIC"
const KEY_FULLSCREEN = "KEY_FULLSCREEN"
const KEY_RESUME = "KEY_RESUME"
const KEY_ITEMS = "KEY_ITEMS"
const KEY_CHICKEN_TITLE = "KEY_CHICKEN_TITLE"
const KEY_CHICKEN_DESCRIPTION = "KEY_CHICKEN_DESCRIPTION"
const KEY_BOOT_TITLE = "KEY_BOOT_TITLE"
const KEY_BOOT_DESCRIPTION = "KEY_BOOT_DESCRIPTION"
const KEY_EYE_TITLE = "KEY_EYE_TITLE"
const KEY_EYE_DESCRIPTION = "KEY_EYE_DESCRIPTION"
const KEY_SWORD_TITLE = "KEY_SWORD_TITLE"
const KEY_SWORD_DESCRIPTION = "KEY_SWORD_DESCRIPTION"
const KEY_GLASSES_TITLE = "KEY_GLASSES_TITLE"
const KEY_GLASSES_DESCRIPTION = "KEY_GLASSES_DESCRIPTION"
const KEY_LUCKY_TITLE = "KEY_LUCKY_TITLE"
const KEY_LUCKY_DESCRIPTION = "KEY_LUCKY_DESCRIPTION"
const KEY_CORE_TITLE = "KEY_CORE_TITLE"
const KEY_CORE_DESCRIPTION = "KEY_CORE_DESCRIPTION"
const KEY_SHIELD_TITLE = "KEY_SHIELD_TITLE"
const KEY_SHIELD_DESCRIPTION = "KEY_SHIELD_DESCRIPTION"
const KEY_DTOOTH_TITLE = "KEY_DTOOTH_TITLE"
const KEY_DTOOTH_DESCRIPTION = "KEY_DTOOTH_DESCRIPTION"
const KEY_HTOOTH_TITLE = "KEY_HTOOTH_TITLE"
const KEY_HTOOTH_DESCRIPTION = "KEY_HTOOTH_DESCRIPTION"
const KEY_NUMBER_TITLE = "KEY_NUMBER_TITLE"
const KEY_NUMBER_DESCRIPTION = "KEY_NUMBER_DESCRIPTION"
const KEY_GORILKA_TITLE = "KEY_GORILKA_TITLE"
const KEY_GORILKA_DESCRIPTION = "KEY_GORILKA_DESCRIPTION"
const KEY_TUTORIAL = "KEY_TUTORIAL"

const KEYS = [
 "KEY_NAME",
 "KEY_PLAY",
 "KEY_SETTINGS",
 "KEY_LANGUAGE",
 "KEY_BACK",
 "KEY_QUIT",
 "KEY_TITLE",
 "KEY_SINGLE_MODE",
 "KEY_COOPERATIVE_MODE",
 "KEY_AUTHORS",
 "KEY_RETRY",
 "KEY_GAME_OVER",
 "KEY_MENU",
 "KEY_MODE",
 "KEY_EFFECTS",
 "KEY_MUSIC",
 "KEY_FULLSCREEN",
 "KEY_RESUME",
 "KEY_ITEMS",
 "KEY_CHICKEN_TITLE",
 "KEY_CHICKEN_DESCRIPTION",
 "KEY_BOOT_TITLE",
 "KEY_BOOT_DESCRIPTION",
 "KEY_EYE_TITLE",
 "KEY_EYE_DESCRIPTION",
 "KEY_SWORD_TITLE",
 "KEY_SWORD_DESCRIPTION",
 "KEY_GLASSES_TITLE",
 "KEY_GLASSES_DESCRIPTION",
 "KEY_LUCKY_TITLE",
 "KEY_LUCKY_DESCRIPTION",
 "KEY_CORE_TITLE",
 "KEY_CORE_DESCRIPTION",
 "KEY_SHIELD_TITLE",
 "KEY_SHIELD_DESCRIPTION",
 "KEY_DTOOTH_TITLE",
 "KEY_DTOOTH_DESCRIPTION",
 "KEY_HTOOTH_TITLE",
 "KEY_HTOOTH_DESCRIPTION",
 "KEY_NUMBER_TITLE",
 "KEY_NUMBER_DESCRIPTION",
 "KEY_GORILKA_TITLE",
 "KEY_GORILKA_DESCRIPTION",
 "KEY_TUTORIAL"
]
